package de.secondparts.model.enums;

public enum CategoryEnum {
    ABGASANLAGE,
    KARROSERI,
    RADIO_AUDIO_INFOTAINMENT,
    BELUCHTUNG_LICHTANLAGE,
    KONTAKTE,
    SCHLIESSSYSTEM_VERRIEGELUNG,
    ELEKTRONISCHE_TEILE,
    KRATSTOFFSYSTEM,
    SPIGEL,
    FAHRWERK,
    KUHLSYSTEM,
    WERKZEUGE_GEREATE,
    GETRIBE_ANTRIEB,
    LENKUNG,
    WISCHER,
    HEIZUNG_KLIMAANLAGE,
    MOTOR_MOTORTEILE,
    INNENAUSSTATTUNG,
    RAEDER_BREMSANLAGE

}
